// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-oDawJZk4L0_cyuPmjWRQfHbj2bxUP6g',
    appId: '1:879140539528:web:50065d24d667a75d65633d',
    messagingSenderId: '879140539528',
    projectId: 'sample-firebase-ai-app-14768',
    authDomain: 'sample-firebase-ai-app-14768.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-14768.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi5j4Yy5xTXc02QevYTMI88kow-UVqPOc',
    appId: '1:879140539528:android:0bcde5ba45d7b07665633d',
    messagingSenderId: '879140539528',
    projectId: 'sample-firebase-ai-app-14768',
    storageBucket: 'sample-firebase-ai-app-14768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrf8bifA-iUXJhPvfqJaW1ZAh8wCPFNJc',
    appId: '1:879140539528:ios:115402c9473eb4f165633d',
    messagingSenderId: '879140539528',
    projectId: 'sample-firebase-ai-app-14768',
    storageBucket: 'sample-firebase-ai-app-14768.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );
}
